version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: feature-matrix-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: feature-matrix
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - feature-matrix-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feature-matrix-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/feature-matrix?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-feature-matrix-production-2024
      - JWT_EXPIRE=30d
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - feature-matrix-network
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: feature-matrix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - feature-matrix-network

volumes:
  mongodb_data:
    driver: local

networks:
  feature-matrix-network:
    driver: bridge